steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$finance-bot/$REPO_NAME:$SHORT_SHA', '.']
    env:
      - 'finance-bot=$finance-bot'
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['run', 'deploy', '<finance-bot>',
           '--image', 'gcr.io/$finance-bot/$REPO_NAME:$SHORT_SHA',
           '--region', '<us-central1>',
           '--platform', 'managed',
           '--allow-unauthenticated']
    env:
      - 'finance-bot=$finance-bot'

images:
  - 'gcr.io/$finance-bot/$REPO_NAME:$SHORT_SHA'
