steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$finance-bot/$REPO_NAME:$SHORT_SHA', '.']
    env:
      - 'finance-bot=$finance-bot'

images:
  - 'gcr.io/$finance-bot/$REPO_NAME:$SHORT_SHA'
